export { default as EnglishAnime } from '../components/english/EnglishAnime'
export { default as PopularTVshow } from '../components/english/PopularTvshow'
export { default as EnglisDrama } from '../components/english/EnglishDrama'
export { default as EnglishMystrey } from '../components/english/EnglishMystrey'
export { default as EnglishCrime } from '../components/english/EnglishCrime'
export { default as Englishcomedy } from '../components/english/Englishcomedy'
export { default as EnglishRomance } from '../components/english/EnglishRomance'
export { default as EnglishFamily } from '../components/english/EnglishFamily'
export { default as EnglishDoc } from '../components/english/EnglishDoc'
export { default as Englishmusic } from '../components/english/EnglishMusic'
export { default as EnglishHistory } from '../components/english/EnglishHistory'
export { default as EnglishWestern } from '../components/english/EnglishWestern'



export { default as PopularHindiTvshow } from '../components/hindi/PopularHindiTvshow'
export { default as HindiDoc } from '../components/hindi/HindiDoc'
export { default as HindiComedy } from '../components/hindi/HindiComedy'
export { default as HindiCrime } from '../components/hindi/HindiCrime'
export { default as HindiAnime } from '../components/hindi/HindiAnime'